development:
  site_title: sso test

  #google_oauth2_client_id: '1095898423613-khq6ltoa6objkiagpjkobjilrpubb0qq.apps.googleusercontent.com'
  #google_oauth2_client_secret: 'UBJThs0nsizb4vKeMqID3ULm'
  #google_openid_realm: "http://localhost:3002"
  # use_ldap:
  #   title: Curoverse LDAP
  #   host: ldap.curoverse.com
  #   port: 636
  #   method: ssl
  #   base: "ou=Users, dc=curoverse, dc=com"
  #   uid: uid
  #   email_domain: curoverse.com
  #   #bind_dn: "some_user"
  #   #password: "some_password"

  allow_account_registration: true
  require_email_confirmation: true